import { bati, cOcsVegetation } from "../../styles/PLAN.IGN/modern/vars";

const sprite: Sprite = {
  name: "basic",
  width: 512,
  height: 584,
  items: {
    "foret-coni": {
      x: 0,
      y: 0,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "foret-coni.svg",
      searchAndReplace: [
        ["#cccccc", cOcsVegetation.foretConi[0]],
        ["#000000", cOcsVegetation.foretConi[1]],
      ],
    },
    "foret-feuil": {
      x: 128,
      y: 0,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "foret-feuil.svg",
      searchAndReplace: [
        ["#cccccc", cOcsVegetation.foretFeuil[0]],
        ["#000000", cOcsVegetation.foretFeuil[1]],
      ],
    },
    "foret-mixte": {
      x: 256,
      y: 0,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "foret-mixte.svg",
      searchAndReplace: [
        ["#cccccc", cOcsVegetation.foret[0]],
        ["#000000", cOcsVegetation.foret[1]],
      ],
    },
    "lande-ligneuse": {
      x: 384,
      y: 0,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "lande-ligneuse.svg",
      searchAndReplace: [
        ["#cccccc", cOcsVegetation.landeLigneuse[0]],
        ["#000000", cOcsVegetation.landeLigneuse[1]],
      ],
    },
    sable: {
      x: 0,
      y: 128,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "sable.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.sable[1]],
        ["#cccccc", cOcsVegetation.sable[0]],
      ],
    },
    "sable-humide": {
      x: 128,
      y: 128,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "sable-humide.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.sableHumide[1]],
        ["#cccccc", cOcsVegetation.sableHumide[0]],
      ],
    },
    marais: {
      x: 256,
      y: 128,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "marais.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.marais[1]],
        ["#cccccc", cOcsVegetation.marais[0]],
      ],
    },
    "marais-salant": {
      x: 384,
      y: 128,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "marais-salant.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.maraisSalant[1]],
        ["#cccccc", cOcsVegetation.maraisSalant[0]],
      ],
    },
    graviers: {
      x: 0,
      y: 256,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "graviers.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.graviers[1]],
        ["#cccccc", cOcsVegetation.graviers[0]],
      ],
    },
    "graviers-humides": {
      x: 128,
      y: 256,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "graviers-humides.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.graviersHumides[1]],
        ["#cccccc", cOcsVegetation.graviersHumides[0]],
      ],
    },

    "rocher-hydro": {
      x: 256,
      y: 256,
      width: 128,
      height: 128,
      pixelRatio: 2,
      src: "rocher-hydro.svg",
      searchAndReplace: [
        ["#000000", cOcsVegetation.rocherHydro[1]],
        ["#cccccc", cOcsVegetation.rocherHydro[0]],
      ],
    },
    train: {
      x: 0,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "train.svg",
      searchAndReplace: [["#000000", bati.gare.cText]],
    },
    culte: {
      x: 32,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "culte.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    aeroport: {
      x: 64,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "aeroport.svg",
      searchAndReplace: [["#000000", bati.aeroport.cText]],
    },
    chateau: {
      x: 96,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "chateau.svg",
      searchAndReplace: [["#000000", bati.monument.cText]],
    },
    "station-epuration": {
      x: 128,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "station-epuration.svg",
      searchAndReplace: [["#000000", bati.hydro.cText]],
    },
    "station-pompage": {
      x: 160,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "station-pompage.svg",
      searchAndReplace: [["#000000", bati.hydro.cText]],
    },
    stade: {
      x: 192,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "stade.svg",
      searchAndReplace: [["#000000", bati.sportifAutre.cText]],
    },

    fontaine: {
      x: 224,
      y: 384,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "fontaine.svg",
      searchAndReplace: [["#000000", bati.hydro.cText]],
    },
    abri: {
      x: 0,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "abri.svg",
      searchAndReplace: [["#000000", bati.refuge.cText]],
    },
    question: {
      x: 32,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "question.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },

    barrage: {
      x: 64,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "barrage.svg",
      searchAndReplace: [["#000000", bati.hydro.cText]],
    },
    eolienne: {
      x: 96,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "eolienne.svg",
      searchAndReplace: [["#000000", bati.autre.cText]],
    },
    feu: {
      x: 128,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "feu.svg",
      searchAndReplace: [
        ["#000000", bati.quelconque.cText],
        ["#ffffff", "#ffffff"],
      ],
    },
    hopital: {
      x: 160,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "hopital.svg",
      searchAndReplace: [["#000000", bati.hopital.cText]],
    },
    metro: {
      x: 192,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "metro.svg",
      searchAndReplace: [
        ["#000000", bati.gare.cText],
        ["#ffffff", "#ffffff"],
      ],
    },
    parking: {
      x: 224,
      y: 416,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "parking.svg",
      searchAndReplace: [
        ["#000000", bati.quelconque.cText],
        ["#e6e6e6", bati.quelconque.cFill],
      ],
    },
    ecluse: {
      x: 0,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "ecluse.svg",
      searchAndReplace: [["#000000", bati.hydro.cText]],
    },
    "refuge-garde": {
      x: 32,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "refuge-garde.svg",
      searchAndReplace: [["#000000", bati.refuge.cText]],
    },
    "refuge-non-garde": {
      x: 64,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "refuge-non-garde.svg",
      searchAndReplace: [["#000000", bati.refuge.cText]],
    },
    "religion-chretienne": {
      x: 96,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "religion-chretienne.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    "religion-juive": {
      x: 128,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "religion-juive.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    "religion-musulmane": {
      x: 160,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "religion-musulmane.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    silo: {
      x: 192,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "silo.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },
    reservoir: {
      x: 224,
      y: 448,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "reservoir.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },
    "construction-speciale": {
      x: 0,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "construction-speciale.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },
    croix: {
      x: 32,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "croix.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    chapelle: {
      x: 64,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "chapelle.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    electricite: {
      x: 96,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "electricite.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },
    pov: {
      x: 128,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "point-de-vue.svg",
      searchAndReplace: [["#000000", bati.autre.cText]],
    },
    fortification: {
      x: 160,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "fortification.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },
    monument: {
      x: 192,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "monument.svg",
      searchAndReplace: [["#000000", bati.monument.cText]],
    },
    priere: {
      x: 224,
      y: 480,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "priere.svg",
      searchAndReplace: [["#000000", bati.culte.cText]],
    },
    "station-eau": {
      x: 0,
      y: 512,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "station-eau.svg",
      searchAndReplace: [["#000000", bati.hydro.cText]],
    },
    cimetiere: {
      x: 32,
      y: 512,
      width: 32,
      height: 32,
      pixelRatio: 2,
      src: "cimetiere.svg",
      searchAndReplace: [
        ["#000000", bati.quelconque.cText],
        ["#e6e6e6", bati.quelconque.cFill],
      ],
    },
    /****************************** */
    glacier: {
      x: 256,
      y: 384,
      width: 152,
      height: 60,
      pixelRatio: 2,
      src: "glacier.png",
    },
    balise: {
      x: 408,
      y: 384,

      width: 64,
      height: 64,
      pixelRatio: 2,
      src: "balise.svg",
      searchAndReplace: [["#000000", bati.autre.cText]],
    },
    barriere: {
      x: 472,
      y: 384,
      width: 21,
      height: 21,
      pixelRatio: 2,
      src: "barriere.svg",
      searchAndReplace: [["#000000", bati.quelconque.cText]],
    },

    phare: {
      x: 256,
      y: 444,
      width: 48,
      height: 64,
      pixelRatio: 2,
      src: "phare.svg",
      searchAndReplace: [["#000000", bati.autre.cText]],
    },
    rocher: {
      x: 304,
      y: 444,
      width: 208,
      height: 140,
      pixelRatio: 2,
      src: "rocher.png",
    },
  },
};

export default sprite;
