import { LayerGroupFactory } from "./types";

export const g020_ocs: LayerGroupFactory = (vars) => {
  const { cOcsBati, cOcsVegetation } = vars;
  return [
    {
      id: "ocs - vegetation",
      type: "fill",
      source: "plan_ign",
      "source-layer": "ocs_vegetation_surf",
      minzoom: 7,
      maxzoom: 20,
      paint: {
        "fill-color": [
          "match",
          ["get", "symbo"],
          ["ZONE_BOISEE", "ZONE_FORET_FERMEE_MIXTE"],
          cOcsVegetation.foret[0],
          "ZONE_FORET_FERMEE_CONI",
          cOcsVegetation.foretConi[0],
          "ZONE_FORET_FERMEE_FEUIL",
          cOcsVegetation.foretFeuil[0],
          "ZONE_FORET_OUVERTE",
          cOcsVegetation.foretOuverte,
          "ZONE_PEUPLERAIE",
          cOcsVegetation.peupleraie,
          "ZONE_LANDE_LIGNEUSE",
          cOcsVegetation.landeLigneuse[0],
          "ZONE_VIGNE",
          cOcsVegetation.vigne,
          "ZONE_VERGER",
          cOcsVegetation.verger,
          "ZONE_CANNE_BANANE",
          cOcsVegetation.canneBanane,
          "ZONE_D_ESTRAN",
          cOcsVegetation.estran,
          "ZONE_MANGROVE",
          cOcsVegetation.mangrove,
          "transparent",
        ],
      },
    },
    {
      id: "ocs - vegetation - forêt",
      type: "fill",
      source: "plan_ign",
      "source-layer": "ocs_vegetation_surf",
      minzoom: 13,
      maxzoom: 20,
      filter: [
        "match",
        ["get", "symbo"],
        ["ZONE_FORET_FERMEE_CONI", "ZONE_FORET_FERMEE_FEUIL", "ZONE_FORET_FERMEE_MIXTE", "ZONE_LANDE_LIGNEUSE"],
        true,
        false,
      ],
      layout: { visibility: "visible" },
      paint: {
        "fill-pattern": [
          "match",
          ["get", "symbo"],
          "ZONE_FORET_FERMEE_CONI",
          "foret-coni",
          "ZONE_FORET_FERMEE_FEUIL",
          "foret-feuil",
          "ZONE_FORET_FERMEE_MIXTE",
          "foret-mixte",
          "ZONE_LANDE_LIGNEUSE",
          "lande-ligneuse",
          "blank",
        ],
      },
    },
    {
      id: "ocs - vegetation - marais",
      type: "fill",
      source: "plan_ign",
      "source-layer": "ocs_vegetation_surf",
      minzoom: 10,
      maxzoom: 13,
      filter: ["match", ["get", "symbo"], ["ZONE_MARAIS", "ZONE_MARAIS_SALANT"], true, false],
      layout: { visibility: "visible" },
      paint: {
        "fill-pattern": [
          "match",
          ["get", "symbo"],
          "ZONE_MARAIS",
          "marais",
          "ZONE_MARAIS_SALANT",
          "marais-salant",
          "TODO",
        ],
      },
    },

    {
      id: "ocs - Zone",
      type: "fill",
      source: "plan_ign",
      "source-layer": "ocs_nature_sol_surf",
      minzoom: 13,
      maxzoom: 20,
      filter: ["==", ["get", "symbo"], "ZONE_ROCHEUSE"],
      layout: { visibility: "visible" },
      paint: { "fill-opacity": 0.7, "fill-pattern": "rocher" },
    },
    {
      /**
       * voir bretagne
       */
      id: "ocs - Zone avec motif",
      type: "fill",
      source: "plan_ign",
      "source-layer": "ocs_nature_sol_surf",
      minzoom: 10,
      maxzoom: 20,
      filter: [
        "match",
        ["get", "symbo"],
        [
          "ZONE_SABLE_SEC",
          "FOND_CUVETTE_HUMIDE",
          "ZONE_SABLE_HUMIDE",
          "GRAVIERS_GALETS_SEC",
          "GRAVIERS_GALETS_HUM",
          "ZONE_ROCHER_HYDRO",
        ],
        true,
        false,
      ],
      paint: {
        "fill-pattern": [
          "match",
          ["get", "symbo"],
          "ZONE_SABLE_SEC",
          "sable",
          ["FOND_CUVETTE_HUMIDE", "ZONE_SABLE_HUMIDE"],
          "sable-humide",
          "GRAVIERS_GALETS_SEC",
          "graviers",
          "GRAVIERS_GALETS_HUM",
          "graviers-humides",
          "ZONE_ROCHER_HYDRO",
          "rocher-hydro",
          "blank",
        ],
      },
    },
    {
      id: "ocs - Zone glacier",
      type: "fill",
      source: "plan_ign",
      "source-layer": "ocs_nature_sol_surf",
      minzoom: 10,
      maxzoom: 13,
      filter: ["==", ["get", "symbo"], "ZONE_GLACIER"],
      layout: { visibility: "visible" },
      paint: {
        "fill-pattern": "glacier",
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 10, 0.5, 12, 0.3],
      },
    },
    /**
     * placé bien en amont des autres bati_zone_surf car il s'agit d'une grosse zone
     * comme il est opaque cela peut masquer beaucoup de composants.
     */
    {
      id: "zone d'activité",
      type: "fill",
      source: "plan_ign",
      "source-layer": "bati_zone_surf",
      minzoom: 10,
      maxzoom: 13,
      filter: ["==", ["get", "symbo"], "ZONE_INDUS_ACTI"],
      layout: { visibility: "visible" },
      paint: { "fill-color": cOcsBati.indusActi },
    },
  ];
};
