import { LayerGroupFactory } from "./types";

/**
 * ZAI : Zone d'activité ou d'intérêt
 */

export const g095_bati_surf: LayerGroupFactory = (vars) => {
  const { bati } = vars;
  return [
    {
      id: "bati surfacique - remplissage",
      type: "fill",
      source: "plan_ign",
      "source-layer": "bati_surf",
      minzoom: 13,
      filter: ["!=", ["get", "symbo"], "BATI_QQUE"],
      paint: {
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0, 14, 1],
        "fill-color": [
          "match",
          ["get", "symbo"],
          ["MAIRIE", "MAIRIE_ANNEXE"],
          bati.mairie.cFill,
          ["BATI_COMMERCIAL", "BATI_INDUSTRIEL", "HANGAR", "HANGAR_COMMERCIAL", "HANGAR_INDUSTRIEL"],
          bati.commerce.cFill,
          "BATI_SPORTIF",
          bati.sportif.cFill,
          "BATI_GARE",
          bati.gare.cFill,
          "PECHERIE_SURF",
          bati.pecherie.cFill,
          ["BATI_PUBLIC", "HANGAR_PUBLIC"],
          bati.public.cFill,
          [
            "AUTRE_CULTE_SURF",
            "CHAPELLE_SURF",
            "CHRETIEN_SURF",
            "EGLISE_SURF",
            "MOSQUEE_SURF",
            "RELIGIEUX_QQUE",
            "SYNAGOGUE_SURF",
          ],
          bati.culte.cFill,
          ["ECLUSE_SURF", "RESERVOIR_EAU_SURF"],
          bati.ecluse.cFill,
          "BARRAGE_SURF",
          bati.barrage.cFill,
          "CHATEAU_EAU_SURF",
          bati.hydro.cFill,
          "SILO_SURF",
          bati.silo.cFill,
          "RESERVOIR_INDUS_SURF",
          bati.reservoirIndustriel.cFill,
          "SERRE_SURF",
          bati.serre.cFill,
          ["ARC_TRIOMPHE_SURF", "ARENE_THEATRE", "CHATEAU_SURF", "FORTIF_SURF", "MONUMENT_SURF", "TOUR_MOULIN_SURF"],
          bati.monument.cFill,
          ["FOOT_SURF", "MULTI_SPORT_SURF", "NATATION_SURF", "PISTE_SPORT_SURF", "SPORT_INDIF_SURF", "TENNIS_SURF"],
          bati.sportifAutre.cFill,
          ["PISTE_DUR", "PISTE_HERBE"],
          bati.piste.cFill,
          ["CIMETIERE_MILI_SURF", "CIMETIERE_SURF", "NECROPOLE_NATIONALE"],
          bati.cimetiere.cFill,
          "POSTE_ELEC_SURF",
          bati.posteElectrique.cFill,
          bati.autre.cFill,
        ],
      },
    },
    {
      id: "bati surfacique - bati qque remplissage z14",
      type: "fill",
      source: "plan_ign",
      "source-layer": "bati_surf",
      minzoom: 14,
      filter: ["==", ["get", "symbo"], "BATI_QQUE"],
      paint: {
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 14, 0, 15, 1],
        "fill-color": ["match", ["get", "symbo"], "BATI_QQUE", bati.quelconque.cFill, bati.autre.cFill],
      },
    },

    {
      id: "bati surfacique - cimetiere motif",
      type: "fill",
      source: "plan_ign",
      "source-layer": "bati_surf",
      filter: [
        "match",
        ["get", "symbo"],
        ["CIMETIERE_MILI_SURF", "CIMETIERE_SURF", "NECROPOLE_NATIONALE"],
        true,
        false,
      ],
      paint: { "fill-pattern": "cimetiere" },
    },
    {
      id: "bati surfacique - contour",
      type: "line",
      source: "plan_ign",
      "source-layer": "bati_surf",
      minzoom: 13,
      maxzoom: 20,
      filter: ["!=", ["get", "symbo"], "BATI_QQUE"],
      paint: {
        "line-width": ["interpolate", ["linear"], ["zoom"], 15, 0.1, 16, 0.3, 19, 2],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0, 14, 1],

        "line-color": [
          "match",
          ["get", "symbo"],
          ["MAIRIE", "MAIRIE_ANNEXE"],
          bati.mairie.cLine,
          ["BATI_COMMERCIAL", "BATI_INDUSTRIEL", "HANGAR", "HANGAR_COMMERCIAL", "HANGAR_INDUSTRIEL"],
          bati.commerce.cLine,
          "BATI_SPORTIF",
          bati.sportif.cLine,
          "BATI_GARE",
          bati.gare.cLine,
          "PECHERIE_SURF",
          bati.pecherie.cLine,
          ["BATI_PUBLIC", "HANGAR_PUBLIC"],
          bati.public.cLine,
          [
            "AUTRE_CULTE_SURF",
            "CHAPELLE_SURF",
            "CHRETIEN_SURF",
            "EGLISE_SURF",
            "MOSQUEE_SURF",
            "RELIGIEUX_QQUE",
            "SYNAGOGUE_SURF",
          ],
          bati.culte.cLine,
          ["ECLUSE_SURF", "RESERVOIR_EAU_SURF"],
          bati.ecluse.cLine,
          "BARRAGE_SURF",
          bati.barrage.cLine,
          "CHATEAU_EAU_SURF",
          bati.hydro.cLine,
          "SILO_SURF",
          bati.silo.cLine,
          "RESERVOIR_INDUS_SURF",
          bati.reservoirIndustriel.cLine,
          "SERRE_SURF",
          bati.serre.cLine,

          ["ARC_TRIOMPHE_SURF", "ARENE_THEATRE", "CHATEAU_SURF", "FORTIF_SURF", "MONUMENT_SURF", "TOUR_MOULIN_SURF"],
          bati.monument.cLine,
          ["FOOT_SURF", "MULTI_SPORT_SURF", "NATATION_SURF", "PISTE_SPORT_SURF", "SPORT_INDIF_SURF", "TENNIS_SURF"],
          bati.sportifAutre.cLine,
          ["PISTE_DUR", "PISTE_HERBE"],
          bati.piste.cLine,
          ["CIMETIERE_MILI_SURF", "CIMETIERE_SURF", "NECROPOLE_NATIONALE"],
          bati.cimetiere.cLine,
          "POSTE_ELEC_SURF",
          bati.posteElectrique.cLine,
          bati.autre.cLine,
        ],
      },
    },
    {
      id: "bati surfacique - bati qque contour z14",
      type: "line",
      source: "plan_ign",
      "source-layer": "bati_surf",
      minzoom: 14,
      filter: ["==", ["get", "symbo"], "BATI_QQUE"],
      paint: {
        "line-width": ["interpolate", ["linear"], ["zoom"], 15, 0.1, 16, 0.3, 19, 2],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 14, 0, 15, 1],
        "line-color": ["match", ["get", "symbo"], "BATI_QQUE", bati.quelconque.cLine, bati.autre.cLine],
      },
    },
    /**
     * permet surtout de délimiter des zones qui contiennent des batiments zai
     */
    {
      id: "zones bati ZAI",
      type: "fill",
      source: "plan_ign",
      "source-layer": "bati_zai",
      minzoom: 15,
      maxzoom: 20,
      paint: {
        "fill-color": [
          "match",
          ["get", "nature"],
          [
            "Hôtel de collectivité",
            "Hôtel de département",
            "Hôtel de région",
            "Préfecture",
            "Préfecture de région",
            "Sous-préfecture",
          ],
          bati.zai.cFillCommandement,
          bati.zai.cFillDefaut,
        ],
        "fill-opacity": 0.3,
      },
    },
  ];
};
