import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g010_oro: () => LayerSpecification[] = () => {
  return [
    {
      id: "bckgrd",
      type: "fill",
      source: "plan_ign",
      "source-layer": "fond_opaque",
      minzoom: 0,
      layout: { visibility: "visible" },
      paint: { "fill-color": "#FFFFFF", "fill-opacity": 1 },
    },
    {
      id: "ocean - mer",
      type: "fill",
      source: "plan_ign",
      "source-layer": "hydro_surf",
      minzoom: 0,
      maxzoom: 20,
      filter: ["==", ["get", "symbo"], "ZONE_MARINE"],
      paint: {
        "fill-color": "#AAD5E9",
      },
    },
    {
      id: "orographie : relief - 0m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_0"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#D6E5BA", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - 100m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_100"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#F7F2DA", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - 200m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_200"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#EBDEBF", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - 1000m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_1000"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#DABE97", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - 3000m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_3000"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#B28773", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - 4000m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_4000"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#9E6A54", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - 5000m",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "HYPSO_5000"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#773A2B", "fill-opacity": 1 },
    },
    {
      id: "orographie : relief - glacier",
      type: "fill",
      source: "plan_ign",
      "source-layer": "oro_relief",
      minzoom: 0,
      filter: ["==", ["get", "symbo"], "GLACIER"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#FFFFFF", "fill-opacity": 0.7 },
    },
  ];
};
