import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g030_oro: () => LayerSpecification[] = () => [
  {
    id: "oro - courbe et cuvette maitresse",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_MAITRESSE", "CUVETTE_MAITRESSE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#D9C8A9",
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 1.7, 15, 2],
    },
  },
  {
    id: "oro - courbe et cuvette normale",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_NORMALE", "CUVETTE_NORMALE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#D9C8A9",
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 1, 15, 1.2],
    },
  },
  {
    id: "oro - courbe et cuvette intercalaire",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_INTERCALAIRE", "CNV_SS_INTERCALAIRE", "CUVETTE_INTERCAL"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#D9C8A9",
      "line-width": 0.7,
      "line-dasharray": [20, 7],
    },
  },
  {
    id: "oro - courbe et cuvette glacier maitresse",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_GLACIER_MAITRESSE", "CUV_GLACIER_MAITRESSE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#A4BFD9",
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 1.7, 15, 2],
    },
  },
  {
    id: "oro - courbe et cuvette glacier normale",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_GLACIER_NORMALE", "CUV_GLACIER_NORMALE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#A4BFD9",
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 1, 15, 1.2],
    },
  },
  {
    id: "oro - courbe et cuvette glacier intercalaire",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_GLACIER_INTERCAL", "CUV_GLACIER_INTERCAL"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#A4BFD9",
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 0.7, 15, 0.9],
      "line-dasharray": [20, 7],
    },
  },
  {
    id: "oro - courbe et cuvette rocher maitresse",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_ROCHER_MAITRESSE", "CUV_ROCHER_MAITRESSE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: { "line-color": "#AAAAAA", "line-width": 1.7 },
  },
  {
    id: "oro - courbe et cuvette rocher normale",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_ROCHER_NORMALE", "CUV_ROCHER_NORMALE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: { "line-color": "#AAAAAA", "line-width": 1 },
  },
  {
    id: "oro - courbe et cuvette rocher intercalaire",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_ROCHER_INTERCAL", "CUV_ROCHER_INTERCAL"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#AAAAAA",
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 0.7, 15, 0.9],
      "line-dasharray": [20, 7],
    },
  },
  {
    id: "oro - courbe et cuvette bathymetrique",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    maxzoom: 16,
    filter: ["match", ["get", "symbo"], ["CNV_BATHYMETRIQUE", "CUV_BATHYMETRIQUE"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: { "line-color": "#0000FF", "line-width": 1 },
  },
  {
    id: "oro lin - talus",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_lin",
    minzoom: 14,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "TALUS"],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: { "line-color": "#D9C8A9", "line-width": 1 },
  },
  {
    id: "oro lin - talus - trait perpendiculaire",
    type: "line",
    source: "plan_ign",
    "source-layer": "oro_lin",
    minzoom: 14,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "TALUS"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#D9C8A9",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 7, 16, 9],
      "line-dasharray": [0.1, 1],
      "line-offset": 4,
    },
  },
  {
    id: "toponyme - cote de courbe normale",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "texte"], "0"],
      ["==", ["get", "hors_zone"], true],
      ["match", ["get", "symbo"], ["CNV_MAITRESSE", "CUVETTE_MAITRESSE"], true, false],
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10, 15, 13],
      "text-anchor": "center",
      "text-rotation-alignment": "map",
      "text-pitch-alignment": "viewport",
      "text-keep-upright": false,
      "text-max-angle": 20,
      "text-max-width": 100,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#604A2F",
      "text-halo-width": 0.5,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - cote de courbe rocher",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "texte"], "0"],
      ["==", ["get", "hors_zone"], true],
      ["match", ["get", "symbo"], ["CNV_ROCHER_MAITRESSE", "CUV_ROCHER_MAITRESSE"], true, false],
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10, 15, 13],
      "text-anchor": "center",
      "text-rotation-alignment": "map",
      "text-pitch-alignment": "viewport",
      "text-keep-upright": false,
      "text-max-angle": 20,
      "text-max-width": 100,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#333333",
      "text-halo-width": 0.5,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - cote de courbe glacier",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "oro_courbe",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "texte"], "0"],
      ["==", ["get", "hors_zone"], true],
      ["match", ["get", "symbo"], ["CNV_GLACIER_MAITRESSE", "CUV_GLACIER_MAITRESSE"], true, false],
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10, 15, 13],
      "text-anchor": "center",
      "text-rotation-alignment": "map",
      "text-pitch-alignment": "viewport",
      "text-keep-upright": false,
      "text-max-angle": 20,
      "text-max-width": 100,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#629FD9",
      "text-halo-width": 0.5,
      "text-halo-color": "#FFFFFF",
    },
  },
];
