import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g095_bati_surf: LayerSpecification[] = [
  {
    id: "parcellaire - parcelle surface",
    type: "fill",
    source: "plan_ign",
    "source-layer": "parcellaire_parcelle",
    filter: ["==", ["get", "symbo"], "PARCELLE"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#FFFFD1", "fill-opacity": 0.7 },
  },

  {
    id: "cimetiere surfacique 1",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["match", ["get", "symbo"], ["CIMETIERE_MILI_SURF", "CIMETIERE_SURF", "NECROPOLE_NATIONALE"], true, false],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": "#F0F0F0",
      "fill-opacity": 0.5,
      "fill-outline-color": "#818181",
    },
  },
  {
    id: "cimetiere surfacique 2",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["match", ["get", "symbo"], ["CIMETIERE_MILI_SURF", "CIMETIERE_SURF", "NECROPOLE_NATIONALE"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-pattern": "Cimetiere" },
  },
  {
    id: "bati surfacique mairie - Zoom 14",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    maxzoom: 14,
    filter: ["match", ["get", "symbo"], ["MAIRIE", "MAIRIE_ANNEXE"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#FFA6A6" },
  },
  {
    id: "bati surfacique mairie - Zoom 15,16,17,18",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 14,
    filter: ["match", ["get", "symbo"], ["MAIRIE", "MAIRIE_ANNEXE"], true, false],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 14, "#FFA6A6", 15, "#FFAEAE"],
      "fill-outline-color": "#FF7C7C",
    },
  },
  {
    id: "bati surfacique fonctionnel industriel ou commercial - Zoom 14,15",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    maxzoom: 15,
    filter: [
      "match",
      ["get", "symbo"],
      ["BATI_COMMERCIAL", "BATI_INDUSTRIEL", "HANGAR", "HANGAR_COMMERCIAL", "HANGAR_INDUSTRIEL"],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#C8C8C8" },
  },
  {
    id: "bati surfacique fonctionnel industriel ou commercial - Zoom 16,17,18",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 15,
    filter: [
      "match",
      ["get", "symbo"],
      ["BATI_COMMERCIAL", "BATI_INDUSTRIEL", "HANGAR", "HANGAR_COMMERCIAL", "HANGAR_INDUSTRIEL"],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 15, "#D1D1D1", 16, "#E6E6E6"],
      "fill-outline-color": "#B8B8B8",
    },
  },
  {
    id: "bati surfacique fonctionnel public - Zoom 14,15",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    maxzoom: 15,
    filter: ["match", ["get", "symbo"], ["BATI_PUBLIC", "HANGAR_PUBLIC"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#B9B6D6" },
  },
  {
    id: "bati surfacique fonctionnel public - Zoom 16,17,18",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 15,
    filter: ["match", ["get", "symbo"], ["BATI_PUBLIC", "HANGAR_PUBLIC"], true, false],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 15, "#CFC5DE", 16, "#E4DAF3"],
      "fill-outline-color": "#A6A1D6",
    },
  },
  {
    id: "bati surfacique fonctionnel sportif - bordure",
    type: "line",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 15,
    filter: ["==", ["get", "symbo"], "BATI_SPORTIF"],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: { "line-color": "#BCD9AB", "line-width": 4 },
  },
  {
    id: "bati surfacique fonctionnel sportif",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 13,
    filter: ["==", ["get", "symbo"], "BATI_SPORTIF"],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 14, "#C9E1DD", 15, "#DCE6E4"],
    },
  },
  {
    id: "bati surfacique fonctionnel gare - Zoom 14,15",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    maxzoom: 15,
    filter: ["==", ["get", "symbo"], "BATI_GARE"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#B3B5F5" },
  },
  {
    id: "bati surfacique fonctionnel gare - Zoom 16,17,18",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 15,
    filter: ["==", ["get", "symbo"], "BATI_GARE"],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 15, "#BFC1F5", 16, "#CBCDF5"],
      "fill-outline-color": "#9B9EF6",
    },
  },
  {
    id: "bati surfacique quelconque - Zoom 15",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 14,
    maxzoom: 15,
    filter: ["==", ["get", "symbo"], "BATI_QQUE"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#D6C6B8" },
  },
  {
    id: "bati surfacique quelconque - Zoom 16,17,18",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 15,
    filter: ["==", ["get", "symbo"], "BATI_QQUE"],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 15, "#E6E0CF", 16, "#F1EBD9"],
      "fill-outline-color": "#C3AA8E",
    },
  },
  {
    id: "bati hydro surfacique - Autre",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["match", ["get", "symbo"], ["ECLUSE_SURF", "RESERVOIR_EAU_SURF"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#ADCCD9", "fill-outline-color": "#336699" },
  },
  {
    id: "bati hydro surfacique - Pecherie",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["==", ["get", "symbo"], "PECHERIE_SURF"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#BFE2F0", "fill-outline-color": "#509FEF" },
  },
  {
    id: "bati hydro surfacique - Barrage",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["==", ["get", "symbo"], "BARRAGE_SURF"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#FFFFFF", "fill-outline-color": "#464646" },
  },
  {
    id: "bati hydro surfacique - Chateau d'eau",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["==", ["get", "symbo"], "CHATEAU_EAU_SURF"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#1466B2" },
  },
  {
    id: "bati infra surfacique - Silo",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 15,
    filter: ["==", ["get", "symbo"], "SILO_SURF"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#C7A9AA", "fill-outline-color": "#696969" },
  },
  {
    id: "bati infra surfacique - Reservoir indus",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 14,
    filter: ["==", ["get", "symbo"], "RESERVOIR_INDUS_SURF"],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#8D9DAA", "fill-outline-color": "#464646" },
  },
  {
    id: "bati infra surfacique - Serre",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 13,
    filter: ["match", ["get", "symbo"], ["SERRE_SURF"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#CAD6D9", "fill-outline-color": "#8C8C8C" },
  },
  {
    id: "bati infra surfacique - poste electrique",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["match", ["get", "symbo"], ["POSTE_ELEC_SURF"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#7993B6", "fill-opacity": 0.3 },
  },
  {
    id: "bati infra surfacique - poste electrique bord",
    type: "line",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["==", ["get", "symbo"], "POSTE_ELEC_SURF"],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#000000",
      "line-width": ["interpolate", ["linear"], ["zoom"], 12, 0.3, 17, 1.2],
    },
  },
  {
    id: "bati religieux surfacique - Zoom 14",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    maxzoom: 14,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "AUTRE_CULTE_SURF",
        "CHAPELLE_SURF",
        "CHRETIEN_SURF",
        "EGLISE_SURF",
        "MOSQUEE_SURF",
        "RELIGIEUX_QQUE",
        "SYNAGOGUE_SURF",
      ],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#F7CBCB" },
  },
  {
    id: "bati religieux surfacique - Zoom 15,16,17,18",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 14,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "AUTRE_CULTE_SURF",
        "CHAPELLE_SURF",
        "CHRETIEN_SURF",
        "EGLISE_SURF",
        "MOSQUEE_SURF",
        "RELIGIEUX_QQUE",
        "SYNAGOGUE_SURF",
      ],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": ["interpolate", ["linear"], ["zoom"], 14, "#F7CBCB", 15, "#F7E1E1"],
      "fill-outline-color": ["interpolate", ["linear"], ["zoom"], 14, "#F7A8A8", 15, "#F7B7B7"],
    },
  },
  {
    id: "bati remarquable surfacique",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    minzoom: 13,
    filter: [
      "match",
      ["get", "symbo"],
      ["ARC_TRIOMPHE_SURF", "ARENE_THEATRE", "CHATEAU_SURF", "FORTIF_SURF", "MONUMENT_SURF", "TOUR_MOULIN_SURF"],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#9B9B9B", "fill-outline-color": "#6E6E6E" },
  },
  {
    id: "bati sportif surfacique fond",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: [
      "match",
      ["get", "symbo"],
      ["FOOT_SURF", "MULTI_SPORT_SURF", "NATATION_SURF", "PISTE_SPORT_SURF", "SPORT_INDIF_SURF", "TENNIS_SURF"],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#FFFFFF", "fill-outline-color": "#FFFFFF" },
  },
  {
    id: "bati sportif surfacique",
    type: "line",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: [
      "match",
      ["get", "symbo"],
      ["FOOT_SURF", "MULTI_SPORT_SURF", "NATATION_SURF", "PISTE_SPORT_SURF", "SPORT_INDIF_SURF", "TENNIS_SURF"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: { "line-color": "#BCD9AB", "line-width": 2 },
  },
  {
    id: "bati transport surfacique - piste",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_surf",
    filter: ["match", ["get", "symbo"], ["PISTE_DUR", "PISTE_HERBE"], true, false],
    layout: { visibility: "visible" },
    paint: { "fill-color": "#DBDBDB", "fill-outline-color": "#808080" },
  },

  {
    id: "bati ZAI - Autres",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_zai",
    minzoom: 15,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "nature"],
      [
        "Administration centrale de l'Etat",
        "Autre service déconcentré de l'Etat",
        "Autre établissement d'enseignement",
        "Capitainerie",
        "Caserne",
        "Caserne de pompiers",
        "Collège",
        "Divers public ou administratif",
        "Enseignement primaire",
        "Enseignement supérieur",
        "Etablissement extraterritorial",
        "Etablissement hospitalier",
        "Etablissement pénitentiaire",
        "Etablissement thermal",
        "Gendarmerie",
        "Hôpital",
        "Lycée",
        "Maison de retraite",
        "Maison du parc",
        "Musée",
        "Office de tourisme",
        "Palais de justice",
        "Piscine",
        "Police",
        "Poste",
        "Science",
        "Siège d'EPCI",
        "Structure d'accueil pour personnes handicapées",
        "Université",
      ],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": "#E3BFE2",
      "fill-opacity": 0.5,
      "fill-outline-color": "#E39FE1",
    },
  },
  {
    id: "bati ZAI - Commandement",
    type: "fill",
    source: "plan_ign",
    "source-layer": "bati_zai",
    minzoom: 15,
    filter: [
      "match",
      ["get", "nature"],
      [
        "Hôtel de collectivité",
        "Hôtel de département",
        "Hôtel de région",
        "Préfecture",
        "Préfecture de région",
        "Sous-préfecture",
      ],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: {
      "fill-color": "#FF0000",
      "fill-opacity": 0.3,
      "fill-outline-color": "#B40000",
    },
  },
];
