import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g120_routier_aerien: LayerSpecification[] = [
  {
    id: "Chemin superieur - piste cyclable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sup",
    minzoom: 13,
    filter: ["match", ["get", "symbo"], ["PISTE_CYCLABLE_SUP", "VOIE_VERTE_SUP"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#9B5CCC", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1.1, 15, 1.7, 16, 2, 17, 3.5, 18, 6],
      "line-dasharray": [6, 2],
    },
  },
  {
    id: "Chemin superieur - filet exterieur - escalier",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sup",
    minzoom: 14,
    filter: ["==", ["get", "symbo"], "ESCALIER_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#8C7274", 18, "#C8C8C8"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1.75, 15, 3, 16, 4.2, 17, 9.5],
    },
  },
  {
    id: "Chemin superieur - filet interieur - escalier",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sup",
    minzoom: 14,
    filter: ["==", ["get", "symbo"], "ESCALIER_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#FFFFFF",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1, 15, 1.9, 16, 2.7, 17, 5.8],
      "line-dasharray": [1, 0.2],
    },
  },
  {
    id: "Chemin superieur - Rue pietonne",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sup",
    minzoom: 14,
    filter: ["==", ["get", "symbo"], "RUE_PIETONNE_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#8C7274", 18, "#EBEBEB"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1, 15, 1.2, 16, 1.4, 17, 2, 18, 5],
      "line-dasharray": [1, 3],
    },
  },
  {
    id: "Chemin superieur - sentier",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sup",
    minzoom: 13,
    filter: ["==", ["get", "symbo"], "SENTIER_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#8C7274", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1, 15, 1.2, 16, 1.4, 17, 2, 18, 6],
      "line-dasharray": [4, 3],
    },
  },
  {
    id: "Chemin superieur - chemin",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sup",
    minzoom: 12,
    filter: ["==", ["get", "symbo"], "CHEMIN_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#8C7274", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1, 15, 1.2, 16, 1.4, 17, 2, 18, 7],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route non revetu carrosable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "NON_REVETUE_CARRO_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 12, "#646464", 17, "#8C8C8C"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 3.2, 15, 5.4, 16, 7.7, 17, 16.8],
      "line-dasharray": [2, 2],
    },
  },
  {
    id: "Routier superieur - filet extérieur - bretelle autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 12,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_AUTO_LIBRE_1_SUP",
        "BRET_AUTO_LIBRE_2_SUP",
        "BRET_AUTO_LIBRE_3_SUP",
        "BRET_AUTO_PEAGE_1_SUP",
        "BRET_AUTO_PEAGE_2_SUP",
        "BRET_AUTO_PEAGE_3_SUP",
      ],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#DE460E", 17, "#F18800", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 12, 2.5, 14, 3.7, 15, 6.8, 16, 8.4, 17, 14],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route non classee restreint",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    filter: ["==", ["get", "symbo"], "NON_CLASSEE_RESTREINT_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#969696", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 3.2, 15, 5.4, 16, 7.7, 17, 16.8],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route non classee",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    filter: ["match", ["get", "symbo"], ["NON_CLASSEE_4_SUP", "NON_CLASSEE_SUP"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#969696", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 3.2, 15, 5.4, 16, 7.7, 17, 16.8],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route locale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_LOCALE_SUP", "LOCALE_1_SUP", "LOCALE_2_SUP", "LOCALE_3_SUP", "LOCALE_4_SUP"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 12, "#8C8C8C", 13, "#B4B4B4", 17, "#B4B4B4", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 9, 2, 14, 3.5, 15, 6, 16, 8.4, 17, 18.3],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route locale en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 11,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "LOCALE_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#C8C8C8",
      "line-width": ["interpolate", ["linear"], ["zoom"], 9, 2, 14, 3.5, 15, 6, 16, 8.4, 17, 18.3],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route regionale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 8,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_REGIONALE_SUP", "REGIONALE_1_SUP", "REGIONALE_2_SUP", "REGIONALE_3_SUP", "REGIONALE_4_SUP"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#828282", 10, "#B4B4B4", 17, "#B4B4B4", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.5, 9, 2.3, 14, 5, 15, 8.1, 16, 11.2, 17, 22],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route regionale en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 10,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "REGIONALE_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#C8C8C8",
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.5, 9, 2.3, 14, 5, 15, 8.1, 16, 11.2, 17, 22],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route principale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 8,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_PRINCIPALE_SUP", "PRINCIPALE_1_SUP", "PRINCIPALE_2_SUP", "PRINCIPALE_3_SUP", "PRINCIPALE_4_SUP"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 17, "#E2A52A", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.8, 9, 2.7, 14, 5.9, 15, 9, 16, 12.2, 17, 22.5],
    },
  },
  {
    id: "Routier superieur - filet extérieur - route principale en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 10,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "PRINCIPALE_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#C8C8C8",
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.8, 9, 2.7, 14, 5.9, 15, 9, 16, 12.2, 17, 22.5],
    },
  },
  {
    id: "Routier superieur - filet extérieur - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 8,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE_SUP", "AUTOROU_PEAGE_SUP"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#DE460E", 17, "#F18800", 18, "#FFFFFF"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 2.5, 9, 3.5, 14, 7.5, 15, 11, 16, 15, 17, 26],
    },
  },
  {
    id: "Routier superieur - filet extérieur - autoroute en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 10,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "AUTOROU_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#C8C8C8",
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 2.5, 9, 3.5, 14, 7.5, 15, 11, 16, 15, 17, 26],
    },
  },
  {
    id: "Routier superieur - filet interieur - route non revetu carrosable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    filter: ["==", ["get", "symbo"], "NON_REVETUE_CARRO_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#FFFFFF",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 2.3, 15, 4.1, 16, 6.3, 17, 13.5, 18, 16.8],
    },
  },
  {
    id: "Routier superieur - filet interieur - bretelle autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 12,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_AUTO_LIBRE_1_SUP",
        "BRET_AUTO_LIBRE_2_SUP",
        "BRET_AUTO_LIBRE_3_SUP",
        "BRET_AUTO_PEAGE_1_SUP",
        "BRET_AUTO_PEAGE_2_SUP",
        "BRET_AUTO_PEAGE_3_SUP",
      ],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#F18800", 17, "#F2B230"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 12, 1.5, 14, 2.6, 15, 5.2, 16, 6.7, 17, 10.8],
    },
  },
  {
    id: "Routier superieur - filet interieur - route non classee restreint",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "NON_CLASSEE_RESTREINT_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#EDF1FF",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 2.3, 15, 4.1, 16, 6.3, 17, 13.5],
    },
  },
  {
    id: "Routier superieur - filet interieur - route non classee",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: ["match", ["get", "symbo"], ["NON_CLASSEE_4_SUP", "NON_CLASSEE_SUP"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#FFFFFF",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 2.3, 15, 4.1, 16, 6.3, 17, 13.5],
    },
  },
  {
    id: "Routier superieur - filet interieur - route locale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_LOCALE_SUP", "LOCALE_1_SUP", "LOCALE_2_SUP", "LOCALE_3_SUP", "LOCALE_4_SUP"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 12, "#FFFFFF", 13, "#FCF4A8", 17, "#FCF7C1"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 9, 1.3, 14, 2.3, 15, 4.1, 16, 6.1, 17, 13.1],
    },
  },
  {
    id: "Routier superieur - filet interieur - route locale en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 11,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "LOCALE_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 12, "#FFFFFF", 13, "#FCF4A8", 17, "#FCF7C1"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 9, 2, 14, 3.5, 15, 6, 16, 8.4, 17, 18.3],
      "line-dasharray": [2, 2],
    },
  },
  {
    id: "Routier superieur - filet interieur - route regionale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_REGIONALE_SUP", "REGIONALE_1_SUP", "REGIONALE_2_SUP", "REGIONALE_3_SUP", "REGIONALE_4_SUP"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#FFFFFF", 10, "#FDF28B", 17, "#FCF6BD"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.4, 9, 1.5, 14, 3.2, 15, 5.8, 16, 8.3, 17, 16.2],
    },
  },
  {
    id: "Routier superieur - filet interieur - route regionale en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 10,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "REGIONALE_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#FFFFFF", 10, "#FDF28B", 17, "#FCF6BD"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.5, 9, 2.3, 14, 5, 15, 8.1, 16, 11.2, 17, 22],
      "line-dasharray": [2, 2],
    },
  },
  {
    id: "Routier superieur - filet interieur - route principale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_PRINCIPALE_SUP", "PRINCIPALE_1_SUP", "PRINCIPALE_2_SUP", "PRINCIPALE_3_SUP", "PRINCIPALE_4_SUP"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#F3C66D", 17, "#F2DDB3"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 4, 0.5, 6, 1.8, 9, 2.1, 14, 4.4, 15, 7.3, 16, 10, 17, 18.5],
    },
  },
  {
    id: "Routier superieur - filet interieur - route principale en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 10,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "PRINCIPALE_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#F3C66D", 17, "#F2DDB3"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 1.8, 9, 2.7, 14, 5.9, 15, 9, 16, 12.2, 17, 22.5],
      "line-dasharray": [2, 2],
    },
  },
  {
    id: "Routier superieur - filet interieur - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    maxzoom: 18,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE_SUP", "AUTOROU_PEAGE_SUP"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#F18800", 17, "#F2B230"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 4, 0.7, 6, 2.5, 9, 2.7, 14, 5.8, 15, 9, 16, 12, 17, 20.8],
    },
  },
  {
    id: "Routier superieur - axe central - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 13,
    maxzoom: 18,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE_SUP", "AUTOROU_PEAGE_SUP"], true, false],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#FFFFFF",
      "line-width": ["interpolate", ["linear"], ["zoom"], 9, 0.6, 14, 0.7, 15, 1, 16, 1.2, 17, 2.1],
    },
  },
  {
    id: "Routier superieur - filet interieur - autoroute en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 10,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "AUTOROU_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 9, "#F18800", 17, "#F2B230"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 4, 0.7, 6, 2.5, 9, 3.5, 14, 7.5, 15, 11, 16, 15, 17, 26],
      "line-dasharray": [2, 2],
    },
  },
  {
    id: "Routier superieur - axe centrale - autoroute en construction",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sup",
    minzoom: 13,
    maxzoom: 18,
    filter: ["==", ["get", "symbo"], "AUTOROU_CONSTR_SUP"],
    layout: {
      visibility: "visible",
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#808080",
      "line-width": ["interpolate", ["linear"], ["zoom"], 9, 0.6, 14, 0.7, 15, 1, 16, 1.2, 17, 2.1],
    },
  },
];
