import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g160_bati_ponctuel: () => LayerSpecification[] = () => [
  {
    id: "routier ponctuel - barriere",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "routier_ponc",
    minzoom: 12,
    filter: ["==", ["get", "symbo"], "BARRIERE"],
    layout: {
      visibility: "visible",
      "icon-image": "Barriere",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.25, 16, 0.45, 17, 0.7],
      "icon-allow-overlap": true,
      "icon-rotate": ["get", "rotation"],
    },
    paint: { "icon-color": "#969696" },
  },
  {
    id: "hydro ponctuel",
    type: "circle",
    source: "plan_ign",
    "source-layer": "hydro_ponc",
    minzoom: 13,
    filter: [
      "match",
      ["get", "symbo"],
      ["AUTRE_HYDRO_PONC", "CASCADE", "FONTAINE", "PERTE", "POINT_D_EAU", "RESURGENCE", "SOURCE", "SOURCE_CAPTEE"],
      true,
      false,
    ],
    layout: { visibility: "visible" },
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 14, 3, 17, 7],
      "circle-color": "#FFFFFF",
      "circle-opacity": 1,
      "circle-stroke-width": ["interpolate", ["linear"], ["zoom"], 14, 2, 17, 5],
      "circle-stroke-color": "#1466B2",
    },
  },
  {
    id: "point coté",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "oro_ponc",
    minzoom: 11,
    maxzoom: 16,
    filter: [
      "match",
      ["get", "symbo"],
      ["POINT_COTE", "POINT_COTE_RESEAU", "POINT_COTE_TOPO", "POINT_RBF"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.1,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 10,
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.2, 0.4],
      "text-padding": 2,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: { "text-color": "#505050" },
  },
  {
    id: "bati ponctuel : Hopital",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "HOPITAL_PONC"],
    layout: {
      visibility: "visible",
      "icon-image": "Hopital",
      "icon-size": 0.33,
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel hydrographique",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 14,
    filter: [
      "match",
      ["get", "symbo"],
      ["CITERNE", "LAVOIR", "STATION_DE_POMPAGE", "STATION_EPURATION", "USINE_ELEVATRICE", "USINE_PRODUCTION_EAU"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "icon-image": "Pompage",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.2, 17, 0.6],
      "icon-allow-overlap": true,
    },
    paint: { "icon-color": "#1C62A6" },
  },
  {
    id: "bati ponctuel hydrographique - Puits-Abreuvoir",
    type: "circle",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 13,
    filter: ["match", ["get", "symbo"], ["ABREUVOIR", "PUITS"], true, false],
    layout: { visibility: "visible" },
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 14, 3, 17, 7],
      "circle-color": "#FFFFFF",
      "circle-opacity": 1,
      "circle-stroke-width": ["interpolate", ["linear"], ["zoom"], 14, 2, 17, 5],
      "circle-stroke-color": "#1466B2",
    },
  },
  {
    id: "bati ponctuel hydrographique - Phare",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 13,
    filter: ["==", ["get", "symbo"], "PHARE"],
    layout: {
      visibility: "visible",
      "icon-image": "Phare",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.7, 17, 1.3],
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel hydrographique - Amer-Feu",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 13,
    filter: ["match", ["get", "symbo"], ["AMER", "FEU", "FEU_PONC", "TOURELLE_LUMINEUSE"], true, false],
    layout: {
      visibility: "visible",
      "icon-image": "Feu",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.7, 17, 1.3],
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel hydrographique - Balise",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 13,
    filter: ["match", ["get", "symbo"], ["BALISE", "TOURELLE"], true, false],
    layout: {
      visibility: "visible",
      "icon-image": "Balise",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.7, 17, 1.3],
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel hydrographique - Ecluse",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 12,
    maxzoom: 15,
    filter: ["==", ["get", "symbo"], "ECLUSE_PONC"],
    layout: {
      visibility: "visible",
      "icon-image": "Ecluse",
      "icon-size": 0.2,
    },
    paint: { "icon-color": "#1C62A6" },
  },
  {
    id: "bati ponctuel hydrographique - Barrage",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 12,
    maxzoom: 14,
    filter: ["==", ["get", "symbo"], "BARRAGE_PONC"],
    layout: {
      visibility: "visible",
      "icon-image": "Barrage",
      "icon-size": 0.25,
    },
    paint: { "icon-color": "#1C62A6" },
  },
  {
    id: "bati ponctuel hydrographique - Chateau d'eau",
    type: "circle",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "CHATEAU_EAU_PONC"],
    layout: { visibility: "visible" },
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 14, 3, 17, 8],
      "circle-color": "#1466B2",
    },
  },
  {
    id: "bati ponctuel hydrographique - Réservoir d'eau",
    type: "circle",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    maxzoom: 15,
    filter: ["==", ["get", "symbo"], "RESERVOIR_EAU_PONC"],
    layout: { visibility: "visible" },
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 14, 3, 17, 8],
      "circle-color": "#AAD5E9",
      "circle-opacity": 1,
      "circle-stroke-width": ["interpolate", ["linear"], ["zoom"], 14, 1, 17, 2.5],
      "circle-stroke-color": "#1466B2",
    },
  },
  {
    id: "bati ponctuel infrastructure - Constr spé",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: [
      "match",
      ["get", "symbo"],
      [
        "ANTENNE",
        "CHEMINEE",
        "CHEVALEMENT",
        "CONSTR_INDIF_PONC",
        "PUITS_GAZ",
        "PUITS_PETROLE",
        "PYLONE_METEO",
        "TORCHERE",
        "TOUR_GUET",
        "TOUR_HERTZIENNE",
        "TRANSFORMATEUR",
      ],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "icon-image": "ConstrSpeciale",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.22, 17, 0.5],
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel infrastructure - Silo",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    maxzoom: 15,
    filter: ["==", ["get", "symbo"], "SILO_PONC"],
    layout: {
      visibility: "visible",
      "icon-image": "Silo",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.22, 17, 0.5],
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel infrastructure - Eolienne",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "EOLIENNE"],
    layout: {
      visibility: "visible",
      "icon-image": "Eolienne",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.4, 17, 1, 18, 0.8],
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel infrastructure - Reservoir",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    maxzoom: 15,
    filter: ["==", ["get", "symbo"], "RESERVOIR_PONC"],
    layout: {
      visibility: "visible",
      "icon-image": "Reservoir",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.26, 17, 0.5],
    },
    paint: { "icon-color": "#646464" },
  },

  {
    id: "bati ponctuel montagne - Abri",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "ABRI"],
    layout: {
      visibility: "visible",
      "icon-image": "Abri",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.4, 15, 0.6, 17, 0.9],
    },
    paint: { "icon-color": "#246138" },
  },
  {
    id: "bati ponctuel montagne - Refuge Garde",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "REFUGE_GARDE"],
    layout: {
      visibility: "visible",
      "icon-image": "Refugegard",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.4, 15, 0.6, 17, 0.9],
    },
    paint: { "icon-color": "#246138" },
  },
  {
    id: "bati ponctuel montagne - Refuge Non Garde",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "REFUGE"],
    layout: {
      visibility: "visible",
      "icon-image": "Refugenongard",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.4, 15, 0.6, 17, 0.9],
    },
    paint: { "icon-color": "#246138" },
  },
  {
    id: "bati ponctuel transport aerien - Aeroport FXX",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["all", ["==", ["get", "symbo"], "AEROPORT_PONC"], ["==", ["get", "territoire"], "FXX"]],
    layout: {
      visibility: "visible",
      "icon-image": "Aeroport",
      "icon-size": 0.5,
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel transport aerien - Aerodrome FXX",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: [
      "all",
      ["match", ["get", "symbo"], ["AERODROME_IMPORT_PONC", "AERODROME_PONC"], true, false],
      ["==", ["get", "territoire"], "FXX"],
    ],
    layout: {
      visibility: "visible",
      "icon-image": "Aerodrome",
      "icon-size": 0.4,
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel transport aerien - Aeroport DOM",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 8,
    filter: ["all", ["==", ["get", "symbo"], "AEROPORT_PONC"], ["!=", ["get", "territoire"], "FXX"]],
    layout: {
      visibility: "visible",
      "icon-image": "Aeroport",
      "icon-size": 0.5,
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel transport aerien - Aerodrome DOM",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    minzoom: 8,
    filter: ["all", ["==", ["get", "symbo"], "AERODROME_PONC"], ["!=", ["get", "territoire"], "FXX"]],
    layout: {
      visibility: "visible",
      "icon-image": "Aerodrome",
      "icon-size": 0.4,
    },
    paint: { "icon-color": "#646464" },
  },
  {
    id: "bati ponctuel transport ferroviaire",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "bati_ponc",
    filter: ["==", ["get", "symbo"], "GARE_VOYAGEURS"],
    layout: {
      visibility: "visible",
      "icon-image": "Gare",
      "icon-size": 0.33,
    },
    paint: { "icon-color": "#787878" },
  },
];
