import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g170_routier_borne: () => LayerSpecification[] = () => [
  {
    id: "toponyme - bornes postales haute - chemins",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "CHEMIN",
        "CHEMIN_SOU",
        "CHEMIN_SUP",
        "ESCALIER",
        "ESCALIER_SUP",
        "PISTE_CYCLABLE",
        "PISTE_CYCLABLE_SOU",
        "PISTE_CYCLABLE_SUP",
        "RUE_PIETONNE",
        "RUE_PIETONNE_SOU",
        "RUE_PIETONNE_SUP",
        "SENTIER",
        "SENTIER_SOU",
        "SENTIER_SUP",
        "VOIE_VERTE",
        "VOIE_VERTE_SOU",
        "VOIE_VERTE_SUP",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sur"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, -1],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales haute - non revetue, non classee",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "NON_CLASSEE",
        "NON_CLASSEE_4",
        "NON_CLASSEE_4_SUP",
        "NON_CLASSEE_RESTREINT",
        "NON_CLASSEE_RESTREINT_SUP",
        "NON_CLASSEE_SOU",
        "NON_CLASSEE_SUP",
        "NON_REVETUE_CARRO",
        "NON_REVETUE_CARRO_SUP",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sur"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, -1.3],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales haute - locales",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "LOCALE_1",
        "LOCALE_1_SOU",
        "LOCALE_1_SUP",
        "LOCALE_2",
        "LOCALE_2_SOU",
        "LOCALE_2_SUP",
        "LOCALE_3",
        "LOCALE_3_SOU",
        "LOCALE_3_SUP",
        "LOCALE_4",
        "LOCALE_4_SOU",
        "LOCALE_4_SUP",
        "LOCALE_CONSTR",
        "LOCALE_CONSTR_SUP",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sur"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, -1.4],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales haute - regionales",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "REGIONALE_1",
        "REGIONALE_1_SOU",
        "REGIONALE_1_SUP",
        "REGIONALE_2",
        "REGIONALE_2_SOU",
        "REGIONALE_2_SUP",
        "REGIONALE_3",
        "REGIONALE_3_SOU",
        "REGIONALE_3_SUP",
        "REGIONALE_4",
        "REGIONALE_4_SUP",
        "REGIONALE_CONSTR",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sur"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, -1.5],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales haute - principales",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "PRINCIPALE_1",
        "PRINCIPALE_1_SOU",
        "PRINCIPALE_1_SUP",
        "PRINCIPALE_2",
        "PRINCIPALE_2_SOU",
        "PRINCIPALE_2_SUP",
        "PRINCIPALE_3",
        "PRINCIPALE_3_SOU",
        "PRINCIPALE_3_SUP",
        "PRINCIPALE_4",
        "PRINCIPALE_4_SOU",
        "PRINCIPALE_4_SUP",
        "PRINCIPALE_CONSTR",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sur"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, -1.6],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales bas - chemins",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "CHEMIN",
        "CHEMIN_SOU",
        "CHEMIN_SUP",
        "ESCALIER",
        "ESCALIER_SUP",
        "PISTE_CYCLABLE",
        "PISTE_CYCLABLE_SOU",
        "PISTE_CYCLABLE_SUP",
        "RUE_PIETONNE",
        "RUE_PIETONNE_SOU",
        "RUE_PIETONNE_SUP",
        "SENTIER",
        "SENTIER_SOU",
        "SENTIER_SUP",
        "VOIE_VERTE",
        "VOIE_VERTE_SOU",
        "VOIE_VERTE_SUP",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sous"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, 1],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales bas - non revetue, non classee",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "NON_CLASSEE",
        "NON_CLASSEE_4",
        "NON_CLASSEE_4_SUP",
        "NON_CLASSEE_RESTREINT",
        "NON_CLASSEE_RESTREINT_SUP",
        "NON_CLASSEE_SOU",
        "NON_CLASSEE_SUP",
        "NON_REVETUE_CARRO",
        "NON_REVETUE_CARRO_SUP",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sous"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, 1.3],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales bas - locales",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "LOCALE_1",
        "LOCALE_1_SOU",
        "LOCALE_1_SUP",
        "LOCALE_2",
        "LOCALE_2_SOU",
        "LOCALE_2_SUP",
        "LOCALE_3",
        "LOCALE_3_SOU",
        "LOCALE_3_SUP",
        "LOCALE_4",
        "LOCALE_4_SOU",
        "LOCALE_4_SUP",
        "LOCALE_CONSTR",
        "LOCALE_CONSTR_SUP",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sous"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, 1.4],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales bas - regionales",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "REGIONALE_1",
        "REGIONALE_1_SOU",
        "REGIONALE_1_SUP",
        "REGIONALE_2",
        "REGIONALE_2_SOU",
        "REGIONALE_2_SUP",
        "REGIONALE_3",
        "REGIONALE_3_SOU",
        "REGIONALE_3_SUP",
        "REGIONALE_4",
        "REGIONALE_4_SUP",
        "REGIONALE_CONSTR",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sous"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, 1.5],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "toponyme - bornes postales bas - principales",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_routier_borne",
    minzoom: 17,
    maxzoom: 18,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "PRINCIPALE_1",
        "PRINCIPALE_1_SOU",
        "PRINCIPALE_1_SUP",
        "PRINCIPALE_2",
        "PRINCIPALE_2_SOU",
        "PRINCIPALE_2_SUP",
        "PRINCIPALE_3",
        "PRINCIPALE_3_SOU",
        "PRINCIPALE_3_SUP",
        "PRINCIPALE_4",
        "PRINCIPALE_4_SOU",
        "PRINCIPALE_4_SUP",
        "PRINCIPALE_CONSTR",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "borne_sous"]],
      "text-size": 11,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-offset": [0, 1.6],
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#79654F",
      "text-halo-width": 1,
      "text-halo-color": "#FFFFFF",
    },
  },
];
