import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g210_toponyme_hydro: () => LayerSpecification[] = () => [
  {
    id: "toponyme - hydro lineaire ocean",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_lin",
    filter: ["==", ["get", "txt_typo"], "OCEAN_MER"],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 30,
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 4,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - hydro lineaire 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_lin",
    filter: [
      "match",
      ["get", "txt_typo"],
      [
        "HYD-LIN-1",
        "HYD_LIN_1",
        "HYD_SURF_1",
        "HYD_SURF_1_T",
        "TYPO_D_1",
        "TYPO_D_2",
        "TYPO_D_3_T",
        "TYPO_D_4_T",
        "TYPO_D_LIN_1",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 18,
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 2,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - hydro lineaire glacier",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_lin",
    filter: ["match", ["get", "txt_typo"], ["ORO_GLACIER_1", "ORO_GLACIER_2"], true, false],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 15,
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 2,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - hydro lineaire 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_lin",
    filter: [
      "match",
      ["get", "txt_typo"],
      ["HYD_LIN_2", "HYD_SURF_2", "HYD_SURF_2_T", "TYPO_D_4", "TYPO_D_LIN_2"],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 14, 15, 18, 21],
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 2,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - hydro lineaire 4",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_lin",
    minzoom: 14,
    filter: ["match", ["get", "txt_typo"], ["TYPO_D_10", "TYPO_D_6", "TYPO_D_8", "TYPO_D_9"], true, false],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 14, 10, 18, 16],
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 1.5,
      "text-halo-color": "rgba(255, 255, 255, 0.7)",
    },
  },
  {
    id: "toponyme - hydro lineaire 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_lin",
    filter: [
      "match",
      ["get", "txt_typo"],
      [
        "HYD_LIN_3",
        "HYD_LIN_4",
        "HYD_LIN_5",
        "HYD_SURF_3",
        "HYD_SURF_3_T",
        "HYD_SURF_4",
        "HYD_SURF_4_T",
        "HYD_SURF_5",
        "HYD_SURF_5_T",
        "TYPO_D_5",
        "TYPO_D_7",
        "TYPO_D_LIN_3",
        "TYPO_D_LIN_4",
      ],
      true,
      false,
    ],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 14, 12, 18, 19],
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 1.5,
      "text-halo-color": "rgba(255, 255, 255, 0.7)",
    },
  },
  {
    id: "toponyme - hydro ponc 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    minzoom: 4,
    filter: ["match", ["get", "txt_typo"], ["HYD_SURF_1", "TYPO_D_1", "grand", "mer"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 4, 16, 6, 30, 10, 25],
      "text-allow-overlap": true,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme - hydro ponc 2B",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    filter: ["match", ["get", "txt_typo"], ["TYPO_D_3", "TYPO_D_4"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 9, 15, 10, 17, 18, 21],
      "text-allow-overlap": false,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: { "text-color": "#447FB3", "text-halo-color": "#FFFFFF", "text-halo-width": 2 },
  },
  {
    id: "toponyme - hydro ponc 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    minzoom: 5,
    filter: ["match", ["get", "txt_typo"], ["HYD_SURF_2", "TYPO_D_2", "moyen"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 5, 12, 6, 18, 10, 17, 18, 21],
      "text-allow-overlap": false,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: { "text-color": "#447FB3", "text-halo-color": "#FFFFFF", "text-halo-width": 2 },
  },
  {
    id: "toponyme - hydro ponc 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    filter: ["match", ["get", "txt_typo"], ["HYD_SURF_3", "TYPO_D_5", "TYPO_D_6", "TYPO_D_7"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 9, 13, 10, 15, 15, 15, 17, 18],
      "text-allow-overlap": true,
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: { "text-color": "#447FB3", "text-halo-color": "#FFFFFF", "text-halo-width": 2 },
  },
  {
    id: "toponyme - hydro ponc 4",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    filter: [
      "match",
      ["get", "txt_typo"],
      ["HYD_SURF_4", "HYD_SURF_4_T", "HYD_SURF_5", "HYD_SURF_5_T", "SOURCE", "TYPO_D_8"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 14, 13, 17, 16],
      "text-allow-overlap": true,
      "text-padding": 5,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: { "text-color": "#447FB3", "text-halo-color": "#FFFFFF", "text-halo-width": 1 },
  },
  {
    id: "toponyme - hydro ponc glacier",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    filter: ["==", ["get", "txt_typo"], "ORO_GLACIER_2"],
    layout: {
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 14,
      "text-anchor": "center",
      "text-allow-overlap": true,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-width": 2,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - hydro ponc 5",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    filter: ["match", ["get", "txt_typo"], ["TYPO_D_10", "TYPO_D_9", "TYPO_E_1_cyan"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 11, 17, 14],
      "text-allow-overlap": true,
      "text-padding": 5,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: { "text-color": "#447FB3", "text-halo-color": "#FFFFFF", "text-halo-width": 1 },
  },
];
