import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g220_toponyme_limite: LayerSpecification[] = [
  {
    id: "toponyme - limite parc ponc 1 et 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_limite_ponc",
    minzoom: 8,
    filter: ["match", ["get", "txt_typo"], ["LIM_PARC_1", "LIM_PARC_2", "PARC_1", "PARC_2"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 15,
      "text-allow-overlap": false,
      "text-padding": 10,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - limite parc marin",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_limite_ponc",
    minzoom: 8,
    filter: ["match", ["get", "txt_typo"], ["PARC_MARIN_1", "PARC_MARIN_2"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 15,
      "text-allow-overlap": false,
      "text-padding": 10,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#2A81A2",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - limite militaire ponc 1 et 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_limite_ponc",
    filter: ["match", ["get", "txt_typo"], ["LIM_MILI_1", "LIM_MILI_2"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 15,
      "text-allow-overlap": false,
      "text-padding": 5,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#0D2000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - limite parc ponc 3 et 4",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_limite_ponc",
    filter: ["match", ["get", "txt_typo"], ["LIM_PARC_3", "LIM_PARC_4", "RESERVE_NATURELLE_PONC"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 13,
      "text-allow-overlap": false,
      "text-padding": 2,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
  {
    id: "toponyme - limite militaire ponc 3 et 4",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_limite_ponc",
    filter: ["match", ["get", "txt_typo"], ["LIM_MILI_3", "LIM_MILI_4"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 12,
      "text-allow-overlap": false,
      "text-padding": 2,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#0D2000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
];
