import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g240_toponyme_ocs: LayerSpecification[] = [
  {
    id: "toponyme - ocs lineaire 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_lin",
    filter: ["==", ["get", "txt_typo"], "OCS_FORET_1"],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 18, 12, 22],
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-padding": 1,
      "text-max-angle": 45,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-width": 2,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - ocs lineaire 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_lin",
    filter: ["==", ["get", "txt_typo"], "OCS_FORET_2"],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 15, 12, 18],
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-width": 2,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - ocs lineaire 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_lin",
    filter: ["==", ["get", "txt_typo"], "OCS_FORET_3"],
    layout: {
      "symbol-placement": "line",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 12, 12, 15],
      "text-anchor": "center",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-width": 1,
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
    },
  },
  {
    id: "toponyme - ocs ponc 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: ["==", ["get", "txt_typo"], "OCS_FORET_1"],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 18, 12, 22],
      "text-allow-overlap": true,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - ocs ponc 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: ["==", ["get", "txt_typo"], "OCS_FORET_2"],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 15, 12, 18],
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-anchor": "center",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - ocs ponc 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: ["==", ["get", "txt_typo"], "OCS_FORET_3"],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 12, 12, 15],
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-anchor": "center",
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
  {
    id: "toponyme - bois 0",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "BOIS"],
      ["match", ["get", "txt_typo"], ["TYPO_F_2", "TYPO_F_3"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 22,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - bois 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "BOIS"],
      ["match", ["get", "txt_typo"], ["TYPO_F_4", "TYPO_F_5"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 19,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - lieu dit non habité 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "LIEU-DIT_NON_HABITE"],
      ["match", ["get", "txt_typo"], ["TYPO_B_4", "TYPO_B_5"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 15,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
  {
    id: "toponyme - bois 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "BOIS"],
      ["match", ["get", "txt_typo"], ["TYPO_F_6", "TYPO_F_7", "TYPO_F_8"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 16,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme - lieu dit non habité",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "LIEU-DIT_NON_HABITE"],
      ["match", ["get", "txt_typo"], ["TYPO_B_7", "TYPO_B_8", "TYPO_B_9"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 12,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
  {
    id: "toponyme - bois",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "BOIS"],
      ["match", ["get", "txt_typo"], ["TYPO_F_10", "TYPO_F_9"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 13,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#287B00",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
  {
    id: "toponyme - lieu dit non habité 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_ocs_ponc",
    filter: [
      "all",
      ["==", ["get", "symbo"], "LIEU-DIT_NON_HABITE"],
      ["match", ["get", "txt_typo"], ["TYPO_B_10", "TYPO_B_11"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 11,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
    },
  },
];
