import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const g270_toponyme_localite: LayerSpecification[] = [
  {
    id: "toponyme localite n0 typoA4 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["==", ["get", "txt_typo"], "TYPO_A_4"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 17,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 3,
    },
  },
  {
    id: "toponyme localite n0 typoA5etA6 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 18,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["match", ["get", "txt_typo"], ["TYPO_A_5", "TYPO_A_6"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 15, 17, 18],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA7 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 18,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["==", ["get", "txt_typo"], "TYPO_A_7"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 13, 17, 16],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite importance 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 5,
    maxzoom: 13,
    filter: ["match", ["get", "txt_typo"], ["BAT_COMMUNE_3", "BAT_COMMUNE_3_T", "TYPO_A_3", "commune 3"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.21,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 5, 10, 6, 15],
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.3, 0.1],
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA8 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 18,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["==", ["get", "txt_typo"], "TYPO_A_8"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 12, 17, 15],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA9",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    maxzoom: 18,
    filter: ["==", ["get", "txt_typo"], "TYPO_A_9"],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 11.5, 17, 14],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite importance 4",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 7,
    maxzoom: 13,
    filter: ["match", ["get", "txt_typo"], ["BAT_COMMUNE_4", "BAT_COMMUNE_4_T", "TYPO_A_4"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.21,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 13,
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.3, 0.1],
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite importance 5",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 9,
    maxzoom: 13,
    filter: [
      "match",
      ["get", "txt_typo"],
      [
        "BAT_ANCIENNE_COM",
        "BAT_ANCIENNE_COM_T",
        "BAT_CHEF_LIEU_COM",
        "BAT_CHEF_LIEU_COM-T",
        "BAT_CHEF_LIEU_COM_T",
        "BAT_COMMUNE_5",
        "BAT_COMMUNE_5_T",
        "BAT_COMMUNE_ASSOCIEE",
        "BAT_COMMUNE_ASSOCIEE_T",
        "Commune très petite",
        "TYPO_A_5",
      ],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.21,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 11.5,
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.3, 0.1],
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite importance 6et7 - Special DOM",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 7,
    maxzoom: 13,
    filter: ["match", ["get", "txt_typo"], ["TYPO_A_6", "TYPO_A_7"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.21,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 12.5,
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.3, 0.1],
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite hameau ",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 11,
    maxzoom: 13,
    filter: ["match", ["get", "txt_typo"], ["BAT_HAMEAU", "BAT_HAMEAU_T"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.17,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 11,
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.3, 0.1],
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA10",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    maxzoom: 18,
    filter: ["==", ["get", "txt_typo"], "TYPO_A_10"],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 11, 17, 13.5],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typo_E_GE Lieu-dit",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 16,
    maxzoom: 18,
    filter: ["all", ["==", ["get", "symbo"], "LIEU-DIT-HABITE"], ["==", ["get", "txt_typo"], "TYPO_E_GE"]],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 11, 17, 13.5],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typo_E_GE Quartier",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 17,
    maxzoom: 18,
    filter: ["all", ["==", ["get", "symbo"], "QUARTIER"], ["==", ["get", "txt_typo"], "TYPO_E_GE"]],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 11, 17, 13.5],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme quartier ",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    filter: ["match", ["get", "txt_typo"], ["BAT_QUARTIER", "BAT_QUARTIER_T"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 11,
      "text-allow-overlap": false,
      "text-padding": 1,
      "text-font": ["Source Sans Pro Italic"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite importance 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 4,
    maxzoom: 13,
    filter: [
      "match",
      ["get", "txt_typo"],
      ["BAT_COMMUNE-2", "BAT_COMMUNE_2", "BAT_COMMUNE_2_T", "TYPO_A_2", "commune 2"],
      true,
      false,
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.25,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 4, 10, 6, 17],
      "text-allow-overlap": true,
      "text-anchor": "bottom-left",
      "text-offset": [0.3, 0.2],
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": [
        "step",
        ["zoom"],
        ["literal", ["Source Sans Pro Regular"]],
        7,
        ["literal", ["Source Sans Pro Bold"]],
        10,
        ["literal", ["Source Sans Pro Regular"]],
      ],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 3,
    },
  },
  {
    id: "toponyme localite n0 typoA3 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["==", ["get", "txt_typo"], "TYPO_A_3"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 19,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 3,
    },
  },
  {
    id: "toponyme localite n0 typoA2 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["==", ["get", "txt_typo"], "TYPO_A_2"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 21,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme localite n0 typoA8 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 18,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["==", ["get", "txt_typo"], "TYPO_A_8"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 12, 17, 15],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA7 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 18,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["==", ["get", "txt_typo"], "TYPO_A_7"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 13, 17, 16],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA5etA6 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 18,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["match", ["get", "txt_typo"], ["TYPO_A_5", "TYPO_A_6"], true, false],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 15, 15, 17, 18],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 2,
    },
  },
  {
    id: "toponyme localite n0 typoA1 non commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["!=", ["get", "symbo"], "COMMUNE_FUSIONNEE"],
      ["!=", ["get", "symbo"], "COMMUNE_CHEF_LIEU"],
      ["==", ["get", "txt_typo"], "TYPO_A_1"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 23,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme localite n0 typoA4 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["==", ["get", "txt_typo"], "TYPO_A_4"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 17,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 3,
    },
  },
  {
    id: "toponyme localite n0 typoA3 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["==", ["get", "txt_typo"], "TYPO_A_3"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 19,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 3,
    },
  },
  {
    id: "toponyme localite n0 typoA2 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["==", ["get", "txt_typo"], "TYPO_A_2"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 21,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme localite importance 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 3,
    maxzoom: 13,
    filter: ["match", ["get", "txt_typo"], ["BAT_COMMUNE_1", "BAT_COMMUNE_1_T", "TYPO_A_1", "commune 1"], true, false],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "icon-image": "Localite",
      "icon-size": 0.3,
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 3, 10, 6, 20],
      "text-allow-overlap": false,
      "text-anchor": "bottom-left",
      "text-offset": [0.25, -0.1],
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": [
        "step",
        ["zoom"],
        ["literal", ["Source Sans Pro Regular"]],
        7,
        ["literal", ["Source Sans Pro Bold"]],
        10,
        ["literal", ["Source Sans Pro Regular"]],
      ],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme localite n0 typoA1 commune",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 13,
    maxzoom: 16,
    filter: [
      "all",
      ["match", ["get", "symbo"], ["COMMUNE_CHEF_LIEU", "COMMUNE_FUSIONNEE"], true, false],
      ["==", ["get", "txt_typo"], "TYPO_A_1"],
    ],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 23,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme - hydro ponc ocean",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_hydro_ponc",
    minzoom: 1,
    filter: ["==", ["get", "txt_typo"], "ocean"],
    layout: {
      visibility: "visible",
      "symbol-placement": "point",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": ["interpolate", ["linear"], ["zoom"], 1, 16, 6, 30],
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 10,
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#447FB3",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme pays 3",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 4,
    maxzoom: 5,
    filter: ["==", ["get", "txt_typo"], "pays 3"],
    layout: {
      visibility: "visible",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 9,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#787878",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme pays 2",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 2,
    maxzoom: 5,
    filter: ["==", ["get", "txt_typo"], "pays 2"],
    layout: {
      visibility: "visible",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 13,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 2,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#787878",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme pays 1",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    minzoom: 2,
    maxzoom: 5,
    filter: ["==", ["get", "txt_typo"], "pays 1"],
    layout: {
      visibility: "visible",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 13,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 2,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Regular"],
    },
    paint: {
      "text-color": "#787878",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
  {
    id: "toponyme continent",
    type: "symbol",
    source: "plan_ign",
    "source-layer": "toponyme_localite_ponc",
    maxzoom: 3,
    filter: ["==", ["get", "txt_typo"], "continent"],
    layout: {
      visibility: "visible",
      "text-field": ["to-string", ["get", "texte"]],
      "text-size": 15,
      "text-allow-overlap": true,
      "text-anchor": "center",
      "text-padding": 1,
      "text-transform": "uppercase",
      "text-font": ["Source Sans Pro Bold"],
    },
    paint: {
      "text-color": "#787878",
      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 4,
    },
  },
];

// console.log(`ancien ${g270_toponyme_localite.length}`);
// console.log(g270_toponyme_localite.map((s) => `${s.id}: ${s.minzoom} -> ${s.maxzoom}`));
