import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";
import {
  autoroute,
  routeLocale,
  routeNonClassee,
  routeNonClasseeRestreint,
  routeNonRevetue,
  routePrincipale,
  routeRegionale,
  sentier,
} from "./vars";

export const g051_routier_souterrain: LayerSpecification[] = [
  {
    id: "cheminSouterrain - piste cyclable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sou",
    minzoom: 13,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "PISTE_CYCLABLE_SOU"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#AB81CC",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1.1, 15, 1.7, 16, 2, 17, 3.5],
      "line-dasharray": [6, 2],
    },
  },
  {
    id: "cheminSouterrain - Rue pietonne, sentier, chemin",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin_sou",
    minzoom: 14,
    maxzoom: 20,
    filter: ["!=", ["get", "symbo"], "PISTE_CYCLABLE_SOU"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": sentier.c,
      "line-width": sentier.w,
      "line-dasharray": [1, 3],
    },
  },

  {
    id: "routierSouterrain - filet extérieur - route non revetu carrosable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 11,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_REVETUE_CARRO_SOU"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": routeNonRevetue.cFiletExt,
      "line-width": routeNonRevetue.wFiletInt,
      "line-dasharray": routeNonRevetue.dashArray,
    },
  },
  {
    id: "routierSouterrain - filet extérieur - bretelle autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 12,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_AUTO_LIBRE_1_SOU",
        "BRET_AUTO_LIBRE_2_SOU",
        "BRET_AUTO_LIBRE_3_SOU",
        "BRET_AUTO_PEAGE_1_SOU",
        "BRET_AUTO_PEAGE_2_SOU",
        "BRET_AUTO_PEAGE_3_SOU",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": autoroute.cFiletExt,
      "line-width": autoroute.wFiletExtBretelle,
    },
  },
  {
    id: "routierSouterrain - filet extérieur - route non classee restreint",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 13,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_CLASSEE_RESTREINT_SOU"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": routeNonClasseeRestreint.cFiletExt,
      "line-width": routeNonClasseeRestreint.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet extérieur - route non classee",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["NON_CLASSEE_4_SOU", "NON_CLASSEE_SOU"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": routeNonClassee.cFiletExt,
      "line-width": routeNonClassee.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet extérieur - route locale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 11,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_LOCALE_SOU", "LOCALE_1_SOU", "LOCALE_2_SOU", "LOCALE_3_SOU", "LOCALE_4_SOU", "LOCALE_CONSTR_SOU"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["LOCALE_CONSTR_SOU"], 0.1, 0.5],
      // "line-color": "rgba(130, 130, 130, 0.5)",
      "line-color": routeLocale.cFiletExt,
      "line-width": routeLocale.wFiletExt,
    },
  },

  {
    id: "routierSouterrain - filet extérieur - route regionale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 7,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_REGIONALE_SOU",
        "REGIONALE_1_SOU",
        "REGIONALE_2_SOU",
        "REGIONALE_3_SOU",
        "REGIONALE_4_SOU",
        "REGIONALE_CONSTR_SOU",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["REGIONALE_CONSTR_SOU"], 0.1, 0.5],
      // "line-color": "rgba(130, 130, 130, 0.5)",
      "line-color": routeRegionale.cFiletExt,
      "line-width": routeRegionale.wFiletExt,
    },
  },
  {
    id: "routierSouterrain - filet extérieur - route principale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 7,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_PRINCIPALE_SOU",
        "PRINCIPALE_1_SOU",
        "PRINCIPALE_2_SOU",
        "PRINCIPALE_3_SOU",
        "PRINCIPALE_4_SOU",
        "PRINCIPALE_CONSTR_SOU",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["PRINCIPALE_CONSTR_SOU"], 0.1, 0.5],
      "line-color": routePrincipale.cFiletExt,
      "line-width": routePrincipale.wFiletExt,
    },
  },
  {
    id: "routierSouterrain - filet extérieur - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 7,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE_SOU", "AUTOROU_PEAGE_SOU", "AUTOROU_CONSTR_SOU"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["AUTOROU_CONSTR_SOU"], 0.1, 0.5],
      "line-color": autoroute.cFiletExt,
      "line-width": autoroute.wFiletExt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - route non revetu carrosable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 11,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_REVETUE_CARRO_SOU"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": "#fff",
      "line-width": routeNonRevetue.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - bretelle autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 12,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_AUTO_LIBRE_1_SOU",
        "BRET_AUTO_LIBRE_2_SOU",
        "BRET_AUTO_LIBRE_3_SOU",
        "BRET_AUTO_PEAGE_1_SOU",
        "BRET_AUTO_PEAGE_2_SOU",
        "BRET_AUTO_PEAGE_3_SOU",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "rgba(255, 255, 255, 0.5)",
      "line-width": autoroute.wFiletIntBretelle,
    },
  },
  {
    id: "routierSouterrain - filet interieur - route non classee restreint",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 13,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_CLASSEE_RESTREINT_SOU"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": "#fff",
      "line-width": routeNonClasseeRestreint.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - route non classee",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["NON_CLASSEE_4_SOU", "NON_CLASSEE_SOU"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": 0.5,
      "line-color": "#fff",
      "line-width": routeNonClassee.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - route locale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 11,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_LOCALE_SOU", "LOCALE_1_SOU", "LOCALE_2_SOU", "LOCALE_3_SOU", "LOCALE_4_SOU", "LOCALE_CONSTR_SOU"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["LOCALE_CONSTR_SOU"], 0.1, 0.5],
      "line-color": "#fff",
      "line-width": routeLocale.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - route regionale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 5,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_REGIONALE_SOU",
        "REGIONALE_1_SOU",
        "REGIONALE_2_SOU",
        "REGIONALE_3_SOU",
        "REGIONALE_4_SOU",
        "REGIONALE_CONSTR_SOU",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["REGIONALE_CONSTR_SOU"], 0.1, 0.5],
      "line-color": "#fff",
      "line-width": routeRegionale.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - route principale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 3,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_PRINCIPALE_SOU",
        "PRINCIPALE_1_SOU",
        "PRINCIPALE_2_SOU",
        "PRINCIPALE_3_SOU",
        "PRINCIPALE_4_SOU",
        "PRINCIPALE_CONSTR_SOU",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["PRINCIPALE_CONSTR_SOU"], 0.1, 0.5],
      "line-color": "#fff",
      "line-width": routePrincipale.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - filet interieur - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 3,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE_SOU", "AUTOROU_PEAGE_SOU", "AUTOROU_CONSTR_SOU"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["AUTOROU_CONSTR_SOU"], 0.1, 0.5],
      "line-color": "#fff",
      "line-width": autoroute.wFiletInt,
    },
  },
  {
    id: "routierSouterrain - axe central - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route_sou",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE_SOU", "AUTOROU_PEAGE_SOU", "AUTOROU_CONSTR_SOU"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["AUTOROU_CONSTR_SOU"], 0.2, 1],
      "line-color": autoroute.cAxeCentral,
      "line-width": autoroute.wAxeCentral,
    },
  },
];
