import { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";
import {
  autoroute,
  chemin,
  cHydroText,
  pont,
  routeLocale,
  routeNonClassee,
  routeNonClasseeRestreint,
  routeNonRevetue,
  routePrincipale,
  routeRegionale,
  sentier,
} from "./vars";

export const g090_routier_a_niveau: LayerSpecification[] = [
  {
    id: "CheminNiveau - piste cyclable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin",
    minzoom: 13,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "PISTE_CYCLABLE"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": "#9B5CCC",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1.1, 15, 1.7, 16, 2, 17, 3.5, 18, 6],
      "line-dasharray": [6, 2],
    },
  },
  {
    id: "CheminNiveau - filet exterieur - escalier",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin",
    minzoom: 14,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "ESCALIER"],
    layout: {
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#8C7274",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1.75, 15, 3, 16, 4.2, 17, 9.5],
    },
  },
  {
    id: "CheminNiveau - filet interieur - escalier",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin",
    minzoom: 14,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "ESCALIER"],
    layout: {
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#FFFFFF",
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 1, 15, 1.9, 16, 2.7, 17, 5.8],
      "line-dasharray": [1, 0.2],
    },
  },
  {
    id: "CheminNiveau - sentier - rue pietonne",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["SENTIER", "RUE_PIETONNE"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": sentier.c,
      "line-width": sentier.w,
      "line-dasharray": [1, 3],
    },
  },
  {
    id: "CheminNiveau - chemin",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_chemin",
    minzoom: 12,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "CHEMIN"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": chemin.c,
      "line-width": chemin.w,
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - route non revetu carrosable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 11,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_REVETUE_CARRO"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeNonRevetue.cFiletExt,
      "line-width": routeNonRevetue.wFiletExt,
      "line-dasharray": routeNonRevetue.dashArray,
    },
  },

  {
    id: "RoutierNiveau - filet extérieur - bretelle autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 12,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_AUTO_LIBRE_1",
        "BRET_AUTO_LIBRE_2",
        "BRET_AUTO_LIBRE_3",
        "BRET_AUTO_PEAGE_1",
        "BRET_AUTO_PEAGE_2",
        "BRET_AUTO_PEAGE_3",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": autoroute.cFiletExt,
      "line-width": autoroute.wFiletExtBretelle,
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - route non classee restreint",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 13,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_CLASSEE_RESTREINT"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeNonClasseeRestreint.cFiletExt,
      "line-width": routeNonClasseeRestreint.wFiletExt,
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - route non classee",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 13,
    maxzoom: 20,

    filter: ["match", ["get", "symbo"], ["NON_CLASSEE", "NON_CLASSEE_4"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeNonClassee.cFiletExt,
      "line-width": routeNonClassee.wFiletExt,
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - route locale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 9,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_LOCALE", "LOCALE_1", "LOCALE_2", "LOCALE_3", "LOCALE_4", "LOCALE_CONSTR"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeLocale.cFiletExt,
      "line-opacity": ["match", ["get", "symbo"], ["LOCALE_CONSTR"], 0.2, 1],
      "line-width": routeLocale.wFiletExt,
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - route regionale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 8,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_REGIONALE", "REGIONALE_1", "REGIONALE_2", "REGIONALE_3", "REGIONALE_4", "REGIONALE_CONSTR"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeRegionale.cFiletExt,
      "line-width": routeRegionale.wFiletExt,
      "line-opacity": ["match", ["get", "symbo"], ["REGIONALE_CONSTR"], 0.3, 1],
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - route principale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 8,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_PRINCIPALE", "PRINCIPALE_1", "PRINCIPALE_2", "PRINCIPALE_3", "PRINCIPALE_4", "PRINCIPALE_CONSTR"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["PRINCIPALE_CONSTR"], 0.2, 1],
      "line-color": routePrincipale.cFiletExt,
      "line-width": routePrincipale.wFiletExt,
    },
  },
  {
    id: "RoutierNiveau - filet extérieur - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 8,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE", "AUTOROU_PEAGE", "AUTOROU_CONSTR"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["AUTOROU_CONSTR"], 0.2, 1],
      "line-color": autoroute.cFiletExt,
      "line-width": autoroute.wFiletExt,
    },
  },
  {
    id: "RoutierNiveau - filet interieur - route non revetu carrosable",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 11,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_REVETUE_CARRO"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeNonRevetue.cFiletInt,
      "line-width": routeNonRevetue.wFiletInt,
    },
  },
  {
    id: "RoutierNiveau - filet interieur - bretelle autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 12,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      [
        "BRET_AUTO_LIBRE_1",
        "BRET_AUTO_LIBRE_2",
        "BRET_AUTO_LIBRE_3",
        "BRET_AUTO_PEAGE_1",
        "BRET_AUTO_PEAGE_2",
        "BRET_AUTO_PEAGE_3",
      ],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": autoroute.cFiletInt,
      "line-width": autoroute.wFiletIntBretelle,
    },
  },
  {
    id: "RoutierNiveau - filet interieur - route non classee restreint",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 13,
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "NON_CLASSEE_RESTREINT"],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeNonClasseeRestreint.cFiletInt,
      "line-width": routeNonClasseeRestreint.wFiletInt,
    },
  },
  {
    id: "RoutierNiveau - filet interieur - route non classee",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["NON_CLASSEE", "NON_CLASSEE_4"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": routeNonClassee.cFiletInt,
      "line-width": routeNonClassee.wFiletInt,
    },
  },
  {
    id: "RoutierNiveau - filet interieur - route locale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 9,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_LOCALE", "LOCALE_1", "LOCALE_2", "LOCALE_3", "LOCALE_4", "LOCALE_CONSTR"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["LOCALE_CONSTR"], 0.2, 1],
      "line-color": routeLocale.cFiletInt,
      "line-width": routeLocale.wFiletInt,
    },
  },

  {
    id: "RoutierNiveau - filet interieur - route regionale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 5,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_REGIONALE", "REGIONALE_1", "REGIONALE_2", "REGIONALE_3", "REGIONALE_4", "REGIONALE_CONSTR"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["REGIONALE_CONSTR"], 0.2, 1],
      "line-color": routeRegionale.cFiletInt,
      "line-width": routeRegionale.wFiletInt,
    },
  },
  // jusqu'au niveau de zoom 8 il n'y a que le filet intérieur
  {
    id: "RoutierNiveau - filet interieur - route principale",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 3,
    maxzoom: 20,
    filter: [
      "match",
      ["get", "symbo"],
      ["BRET_PRINCIPALE", "PRINCIPALE_1", "PRINCIPALE_2", "PRINCIPALE_3", "PRINCIPALE_4", "PRINCIPALE_CONSTR"],
      true,
      false,
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["PRINCIPALE_CONSTR"], 0.2, 1],
      "line-color": routePrincipale.cFiletInt,
      "line-width": routePrincipale.wFiletInt,
    },
  },
  {
    id: "RoutierNiveau - filet interieur - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 3,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE", "AUTOROU_PEAGE", "AUTOROU_CONSTR"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["AUTOROU_CONSTR"], 0.2, 1],
      "line-color": autoroute.cFiletInt,
      "line-width": autoroute.wFiletInt,
    },
  },
  {
    id: "RoutierNiveau - axe central - autoroute",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_route",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["AUTOROU_LIBRE", "AUTOROU_PEAGE", "AUTOROU_CONSTR"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-opacity": ["match", ["get", "symbo"], ["AUTOROU_CONSTR"], 0.2, 1],
      "line-color": autoroute.cAxeCentral,
      "line-width": autoroute.wAxeCentral,
    },
  },
  /*************************************** */

  {
    id: "liaison routiere - Bac Liaison Maritime",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_liaison",
    minzoom: 7,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["BAC_AUTO", "BAC_LIAISON_MARITIME", "LIAISON_MARITIME"], true, false],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-color": cHydroText,
      "line-width": ["interpolate", ["linear"], ["zoom"], 8, 1, 13, 2.5],
    },
  },

  {
    id: "liaison routiere - Gue route / chemin",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_liaison",
    minzoom: 13,
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["GUE_ROUTE", "GUE_CHEMIN"], true, false],
    layout: {
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": ["interpolate", ["linear"], ["zoom"], 13, "#BEBEBE", 17, "#646464"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 14, 2, 16, 5, 17, 10],
    },
  },

  {
    id: "routierSurfacique",
    type: "fill",
    source: "plan_ign",
    "source-layer": "routier_surf",
    minzoom: 13,
    maxzoom: 20,

    filter: [
      "match",
      ["get", "symbo"],
      ["SURF_ROUT_LOC", "SURF_ROUT_NON_CLA", "SURF_ROUT_PRINC", "SURF_ROUT_REG", "DALLE_DE_PROTECTION"],
      true,
      false,
    ],
    paint: {
      "fill-color": "#FFFFFF",
      "fill-outline-color": "#000000",
      "fill-opacity": ["match", ["get", "symbo"], "DALLE_DE_PROTECTION", 0.5, 1],
    },
  },
  {
    id: "routierSurfacique - Dalle de protection",
    type: "fill",
    source: "plan_ign",
    "source-layer": "routier_surf",
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "DALLE_DE_PROTECTION"],
    paint: {
      "fill-opacity": 0.5,
      "fill-color": "#FFFFFF",
      "fill-outline-color": "#000000",
    },
  },

  // {
  //   id: "routierSurfacique - Parking",
  //   type: "fill",
  //   source: "plan_ign",
  //   "source-layer": "routier_surf",
  //   maxzoom: 20,
  //   filter: ["==", ["get", "symbo"], "PARKING_SURF"],
  //   paint: {
  //     "fill-opacity": 0.8,
  //     "fill-color": "red",
  //     "fill-outline-color": "#918091",
  //   },
  // },
  {
    id: "routierSurfacique - Escalier surfacique",
    type: "fill",
    source: "plan_ign",
    "source-layer": "routier_surf",
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "ESCALIER_SURF"],
    paint: {
      "fill-opacity": 0.8,
      "fill-color": "#FFFFFF",
      "fill-outline-color": "#918091",
    },
  },
  {
    id: "routierSurfacique - Péage surfacique",
    type: "fill",
    source: "plan_ign",
    "source-layer": "routier_surf",
    maxzoom: 20,
    filter: ["==", ["get", "symbo"], "SURF_PEAGE"],
    paint: { "fill-color": "#F2DAAA", "fill-opacity": 0.7, "fill-outline-color": "#E2A52A" },
  },

  {
    id: "routier ponctuel - peage ponctuel",
    type: "circle",
    source: "plan_ign",
    "source-layer": "routier_ponc",
    minzoom: 9,
    maxzoom: 14,
    filter: ["==", ["get", "symbo"], "PEAGE_PONC"],
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 9, 2, 12, 4],
      "circle-color": autoroute.cFiletInt,
      "circle-stroke-width": 1.5,
      "circle-stroke-color": autoroute.cFiletExt,
    },
  },

  {
    id: "liaison routiere - filet extérieur - Pont passerelle",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_liaison",
    filter: ["match", ["get", "symbo"], ["PONT_LIN", "PONT_MOBILE_LIN", "PONT_PASSERELLE"], true, false],
    layout: {
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#C8C8C8",
      "line-width": pont.wFiletExt,
    },
  },
  {
    id: "liaison routiere - filet intérieur - Pont passerelle",
    type: "line",
    source: "plan_ign",
    "source-layer": "routier_liaison",
    maxzoom: 20,
    filter: ["match", ["get", "symbo"], ["PONT_LIN", "PONT_MOBILE_LIN", "PONT_PASSERELLE"], true, false],
    layout: {
      "line-cap": "butt",
      "line-join": "round",
    },
    paint: {
      "line-color": "#FFFFFF",
      "line-width": pont.wFiletInt,
    },
  },
];
